backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: Page
    folder: src/routes
    create: true
    fields:
      - name: title
        label: Title
      - name: image
        label: Social Image
        widget: image
        required: false
      - name: body
        label: Content
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
