backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: Pages
    folder: src/routes
    create: true
    fields:
      - name: title
        label: Title
      - name: nav_label
        label: Navigation Label
      - name: body
        label: Content
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg